version: '3'

services:
    mydb:
        container_name: mydb
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - mongodb_air:/data/db
    test:
        build:
            context: .
            dockerfile: ./test/Dockerfile
        depends_on:
            - mydb
    web:
        build:
            context: .
            dockerfile: ./web/Dockerfile
        ports:
            - "5000:5000"
        depends_on:
            - mydb
volumes:
    mongodb_air:
