version: '3'

services:
    mydb:
        container_name: mydb
        image: andresvidal/rpi3-mongodb3
        ports:
            - '27017:27017'
        volumes:
            - mongodb_air:/data/db
        command: bash -c "mongod --repair && mongod"
    tvoc:
        build:
            context: .
            dockerfile: ./tvoc/Dockerfile
        depends_on:
            - mydb
        devices:
            - /dev/i2c-1:/dev/i2c-1
    web:
        build:
            context: .
            dockerfile: ./web/Dockerfile
        ports:
            - "5000:5000"
        depends_on:
            - mydb
volumes:
    mongodb_air:
