version: '3'

services:
    mydb:
        container_name: mydb
        image: mongo:latest
        env_file:
            - ./env.env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$${MONGODB_USER}
            - MONGO_INITDB_ROOT_PASSWORD=$${MONGODB_PASS}
        ports:
            - '27017:27017'
        volumes:
            - mongodb_air:/data/db
    tvoc:
        build:
            context: .
            dockerfile: ./tvoc/Dockerfile
        depends_on:
            - mydb
    web:
        build:
            context: .
            dockerfile: ./web/Dockerfile
        ports:
            - "5000:5000"
        depends_on:
            - mydb
volumes:
    mongodb_air:
